version: "3.9"
services:
  database:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=
      - KEYCLOAK_ADMIN_PASSWORD=
      - DB_VENDOR=
      - DB_ADDR=
      - DB_DATABASE=
      - DB_USER=
      - DB_SCHEMA=
      - DB_PASSWORD=
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - postgres
      
volumes:
  pgdata:
    driver: local